# Generated by Django 4.1.2 on 2023-08-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customer_profile_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='uploaded_files',
            field=models.ManyToManyField(related_name='customers', to='users.file'),
        ),
    ]
