# Generated by Django 4.1.2 on 2023-08-03 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_file_customer_uploaded_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='uploaded_files',
        ),
        migrations.AddField(
            model_name='file',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
